version: '3'
services:

  davical:
    build: 
      context: .
      args:
        TIME_ZONE: Europe/Paris
    ports:
      - "8050:80"
    environment:
      AMIN_PASSWORD: 1234
      DAVICAL_DBA_PASSWORD: 123456
      DAVICAL_APP_PASSWORD: 654321
      PSQLOPTS: "-U davical_dba -h postgres -p 5432 "
      DBAOPTS: "--dbhost=postgres "
    volumes: 
      - /var/davical/config:/config:ro
    restart: unless-stopped
    depends_on:
       postgres:
        condition: service_healthy
       createdb:
        condition: service_completed_successfully
          #entrypoint: ["tail", "-f", "/dev/null"]
    entrypoint: ["/sbin/apache2_start.sh"]

  createdb:
    build: 
      context: .
      dockerfile: Dockerfile.createdb
      args:
        TIME_ZONE: Europe/Paris
    environment:
      AMIN_PASSWORD: 1234
      DAVICAL_DBA_USER: davical_dba
      DAVICAL_DBA_PASSWORD: 123456
      DAVICAL_APP_USER: davical_app
      DAVICAL_APP_PASSWORD: 654321
      PSQLOPTS: "-U davical_dba -h postgres -p 5432 "
      DBAOPTS: "--dbhost=postgres --dbuser davical_dba --dbpass 123456 "
    depends_on:
       postgres:
        condition: service_healthy
    entrypoint: ["/sbin/initialize_db.sh"]
      #entrypoint: ["tail", "-f", "/dev/null"]


  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: eorihasdfasdf
      DAVICAL_DBA_PASSWORD: 123456
      DAVICAL_APP_PASSWORD: 654321
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "psql -U postgres -c 'select 1'|grep -q 1" ]
      interval: 5s
      timeout: 1s
      retries: 30

